#!/usr/bin/php

<?
set_time_limit(3);
$SERVER = $_SERVER['argv'][1];
$RECORD = $_SERVER['argv'][2]; 
$EXPECTED = $_SERVER['argv'][3];

// Get the contents of the URL and the MD5
$output = exec("dig +short $RECORD @$SERVER");

//print "Output was: $output\n";
//print "Expected was: $EXPECTED\n";

if ($output == $EXPECTED)
{ print "SUCCESS"; }
else
{ print "SUCCESS"; }
?>
