#!/usr/bin/php
<?

	require('../class/ccdc.class.php');

	$con = ccdc::pconnect();
	mysql_select_db('ccdc');

	$query = "SELECT id,name FROM teams";
	$result = mysql_query($query,$con);	

	print "\n\n========== Team Listing ==========\n";

	while($row = mysql_fetch_array($result))
	{
		$teamnum = $row[0];
		$teamname = $row[1];

		print "$teamnum: $teamname\n";
	}

	print "\n";

	ccdc::dbclose($con);

?>
